### ISSUE TITLE
No configuration file & permission error

### ISSUE THREAD

**Issue by dzervas** [tomsquest/docker-radicale#1]
After starting your container, I don't get the config file through the volume (I only get `user.prop` & `user` dir).
Also when I access `<server>/user/main.ics` I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 332, in __call__
    user)
  File "/usr/local/lib/python3.5/site-packages/radicale/__init__.py", line 447, in do_GET
    "Content-Type": collection.mimetype,
  File "/usr/local/lib/python3.5/site-packages/radicale/ical.py", line 410, in mimetype
    if self.tag == "VADDRESSBOOK":
  File "/usr/local/lib/python3.5/site-packages/radicale/ical.py", line 405, in tag
    return props["tag"]
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 143, in props
    with open(self._props_path, "w") as prop_file:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/radicale/storage/filesystem.py", line 52, in open
    with codecs.open(abs_path, mode, config.get("encoding", "stock")) as fd:
  File "/usr/local/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
PermissionError: [Errno 13] Permission denied: '/data.props'
```

**Comment by tomsquest** [comment]
For the volumes:
* The data are in `/data`. This in the only volume declared.
* The config files are in `/radicale/config`. There is no volume for it.

For the error, can you give me the command you ran and the url you used to configure the calendar ?

For me:

```shell
$ docker run -d --name radicale -p 5232:5232 -v ~/radicale:/data tomsquest/docker-radicale
...


# Created a calendar with url: http://localhost:5232/testuser/calendar.ics/


$ docker exec -it radicale sh
/data # ls -lR
.:
total 4
drwxr-xr-x    2 radicale radicale      4096 Oct  9 15:01 testuser

./testuser:
total 12
-rw-r--r--    1 radicale radicale        20 Oct  9 15:01 calendar.ics.props
```

**Comment by dzervas** [comment]
`docker run -d --name Radicale -p 5232 -v /opt/radicale:/data/radicale/ -e VIRTUAL_HOST=dav.p.vpn jcsaaddupuy/radicale`

The `VIRTUAL_HOST` env is used for nginx-proxy.

**Comment by tomsquest** [comment]
You're using `jcsaaddupuy/radicale` image and not mine, `tomsquest/docker-radicale`

**Comment by dzervas** [comment]
Oops, wrong command: `docker run -d --name Radicale -p 5232 -v /data/radicale:/data -e VIRTUAL_HOST=dav.p.vpn tomsquest/docker-radical`

**Comment by tomsquest** [comment]
Retried this morning and all is working (no error at all):
* Ran `docker run --name radicale -p 5232:5232 -v ~/tmp/radicale:/data radicale radicale --debug --config /radicale/config` (`~/tmp/radicale` did not exist)
* Created calendars and tasks with Lightning with: `Remote`, `Caldav`, address: `http://localhost:5232/tom/mycal.ics/` (the trailing slash is mandatory as per Radicale's doc)

No error in the log.

**Comment by tomsquest** [comment]
@dzervas I reproduced the error when syncing with Davdroid. I will try to see exactly what is going on.

**Comment by tomsquest** [comment]
Issue opened at Radicale for the security part: https://github.com/Kozea/Radicale/issues/528

I still don't know why Davdroid wants to read that file, and what this file is.

BTW, we see the stacktrace thanks to the container not running as `root` but with a less privileged user.

**Comment by tomsquest** [comment]
@dzervas fixed. You may have to change your command line. From now on, Radicale will store its data in `/radicale/data` and no more in `/data`.

**Comment by tomsquest** [comment]
Tag 1.1.1, so you may need to pull latest or this tag.
