### ISSUE TITLE
Failed to access by bash container

### ISSUE THREAD

**Issue by CastroGal** [tomsquest/docker-radicale#114]
I wanted to access by bash but it gives an error
`pi@raspberrypi:~ $ docker exec -it radicale bash`
`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown`
Any solution?

**Comment by CastroGal** [comment]
OK, solved
`docker exec -it radicale sh`

**Comment by tomsquest** [comment]
Yes, exactly :+1:
