### ISSUE TITLE
can't create secured users through htpasswd

### ISSUE THREAD

**Issue by wizel10** [tomsquest/docker-radicale#115]
Wanted to create a user for external access, but failed to create through htpasswd:
docker exec -ti radicale htpasswd  -c /users user1
with error "...container process caused: exec: "htpasswd": executable file not found in $PATH..."
Can you confirm htpasswd is available in the container?

**Comment by wizel10** [comment]
Just looking at the Dockerfile, seems  apache2-utils is missing in the apk load (lines 32...).

**Comment by tomsquest** [comment]
The preferred way it to use your host to generate the password file if you need.
We won't add a dependency (making the image larger and increasing the attack surface) for that.

**Comment by Jocomol** [comment]
@tomsquest I think that this should be mentioned in the readme

**Comment by tomsquest** [comment]
Can you make a PR with what you would have liked to find in a section of the Readme?
