### ISSUE TITLE
GitHub Action to test calendars

### ISSUE THREAD

**Issue by leog** [tomsquest/docker-radicale#120]
Hello! First of all, thank you very much for your work, it is a very useful tool.

I was wondering how would a GitHub Action setup would be created around this docker version of Radicale in order to automate having a calendar created to be used by integration tests of a system using CalDav calendars. 

I guess that once a service with Radicale is up, you can always automate creating a calendar through the admin UI, then configuring some events in the calendar programatically (no need to configure a calendar client as it's an automation use case) to then test if the system using CalDav interacts correctly with the calendar. Other than this approach, maybe there is a way to do most of this workflow already through some variable/instruction available from the configuration of the docker version.

Anyway, any guidance would be much appreciated, even if it is to confirm the approach I described :)

**Comment by tomsquest** [comment]
Hi @leog ,

I am understood well, you are proposting to add some end-to-end tests to the test suites to assert that Radicale is working properly.
You imagine a scenario that, given Radicale is running (the container, in the Python test), then some API calls could be made to create a calendar for example.

If I am correct in my understanding, I think this is a good idea!

Do you know/want to give it a try?

**Comment by leog** [comment]
Hi @tomsquest.

Actually, I'm thinking about using radicale to test our integration with CalDav from our system for scheduling, and for that I wanted to know if there is a way to create a calendar spinning up radicale from docker instead of having to automate creating one through the admin website.

**Comment by tomsquest** [comment]
Ah this I don't know personnaly.
BUT, @silaslenz did a PR a while ago and provided a Python snippet to create events:
https://github.com/tomsquest/docker-radicale/pull/77#issuecomment-636482555

I hope this will help.
