### ISSUE TITLE
example of authentication (Caddy, radicale config, or otherwise)

### ISSUE THREAD

**Issue by unusualevent** [tomsquest/docker-radicale#135]
Nice hardened docker image.

It'd be great if you had an example in the readme of adding authentication to it.

e.g., how to add a user & password.

**Comment by BLACK4585** [comment]
I would really like to see how to add new Users. It would be nice to know where the user file is stored, there is nothing in /etc/radicale/.
Thank you.

**Comment by tomsquest** [comment]
The authentication and right management is documented at Radicale's own documentation.
There is this link about the type of authentication: https://radicale.org/v3.html#auth

Basically, you will have to provide a file in the format of htpasswd and place it in `https://radicale.org/v3.html#htpasswd_filename` (default: `/etc/radicale/users`).
You should provide a volume containing that file to this docker image.

You will also have to add a config file for the rights (read, write, read+write...) as per : https://radicale.org/v3.html#authentication-and-rights

If you will like to give it a try, a documentation PR would be welcome!

**Comment by BLACK4585** [comment]
I got it working now.
I already thought of a PR, I will try it.
