### ISSUE TITLE
radicale + agendav + openLDAP

### ISSUE THREAD

**Issue by shroomify-it** [tomsquest/docker-radicale#136]
Hi,

**I'm having trouble seting up agenDAV + radicale to authenticate with OpenLDAP.**

For openLDAP, I use :  image: osixia/openldap:latest, it is running OK.
AgenDAV+ radicale works well via file authentication. I managed to make it work with LDAP too, thanks to https://github.com/marcoh00/radicale-auth-ldap (for Radicale2.0 ?)

**Problem is :** I don't know how to deploy the plugin automatically at docker start. I need to connect to the radicale container to make some changes in attempt to make it work with openLDAP.

It seems someone made the plugin compatible for Radicale3.0 : https://github.com/ricjcosme/radicale-auth-ldap/tree/master 

Can you help me ? At the end, would it be possible to add the steps on the README ?

I'm using docker compose.
Thank you

**Comment by shroomify-it** [comment]
I edited the DockerFile to add a few lines : 

    && python3 -m pip install radicale==$VERSION passlib[bcrypt] \
# my modifications
    && mkdir -p /etc/radicale/plugins \
    && cd /etc/radicale/plugins/ \
    && git clone "https://github.com/ricjcosme/radicale-auth-ldap" \
    && python3 -m pip install ./radicale-auth-ldap \
#end
    && apk del --purge build-dependencies \

**Comment by tomsquest** [comment]
Hi @shroomify-it ,

A bit late to the party, sorry.

What you want is to basically enhance the image, or "extends" it.
You can do so mainly by creating a file that adds stuff to it.
It requires basic knowledge of Docker, so should be easy for you.
Here is the link to the doc: https://github.com/tomsquest/docker-radicale#extending-the-image
