### ISSUE TITLE
New version available

### ISSUE THREAD

**Issue by Skaronator** [tomsquest/docker-radicale#143]
v3.1.9 came out 3 weeks ago. Would be cool to update the image to that version

https://github.com/Kozea/Radicale/releases/tag/v3.1.9

**Comment by Skaronator** [comment]
Oh [3.1.9.1](https://hub.docker.com/layers/tomsquest/docker-radicale/3.1.9.1/images/sha256-e45df19819ea11fea14eec7e465ab351f2dd2a03c715f7013a67998faaa9f508?context=explore) already exist. I was just looking at the GitHub releases

**Comment by tomsquest** [comment]
Sorry, I forgot to create the Github releases.
