### ISSUE TITLE
A small documentation issue

### ISSUE THREAD

**Issue by physx2494** [tomsquest/docker-radicale#145]
> Next, create a `user` file inside config directory. It will be located at `./config/users`

This should be 'users'. I wasted 5 minutes trying various combinations to understand why the app was unable to find the htpaswd file. I wondered whether the file should be located inside the 'users/' directory or if it should be named 'users' and located within '.config/'.

**Comment by tomsquest** [comment]
Hi @physx2494 ,

Nice catch!
This must have been irritating.

Readme corrected.
Do not hesitate to submit a PR directly.
