### ISSUE TITLE
Upgrade to radicale 3.2.0

### ISSUE THREAD

**Issue by TribuneX** [tomsquest/docker-radicale#146]
Do you plan to release a new image for the latest radicale version [3.2.0](https://github.com/Kozea/Radicale/releases/tag/v3.2.0)?

**Comment by tomsquest** [comment]
Hi @TribuneX , 
Yes, I do, just a matter of having the time (I am reinstalling my server, so...). 
I think by next week it will be fine.

**Comment by tomsquest** [comment]
PR #147 is failing due to this.

**Comment by ZingyAwesome** [comment]
The release wasn't in testing or anything but they had an [issue](https://github.com/Kozea/Radicale/issues/1483) with their upload workflow which has now been resolved. The new release should now be on PyPi.

**Comment by tomsquest** [comment]
Hi @ZingyAwesome 

Pushed the new image in testing as `tomsquest/docker-radicale:next`.

I am running with it, and merge if everything is fine.
You can test it also.

**Comment by truppelito** [comment]
I updated to `tomsquest/docker-radicale:next` and seems to be working perfectly so far.

**Comment by tomsquest** [comment]
Released `3.2.0.0` :sparkles: :1st_place_medal: 

#147
