### ISSUE TITLE
Unraid template now available

### ISSUE THREAD

**Issue by nwithan8** [tomsquest/docker-radicale#150]
Just wanted to let you know there is now an Unraid template available to easy-install this container via the Unraid Community Apps store (I just released it, will show up here after ~2 hours when the apps next sync): https://unraid.net/community/apps?q=radicle#r

**Comment by tomsquest** [comment]
Hi @nwithan8 

Nice, I updated the Readme with the link.

I noticed a typo in the title on Unraid, if you can fix it:

![image](https://github.com/tomsquest/docker-radicale/assets/365778/7e5de73d-b7eb-44c4-8d18-0d9860528e96)

**Comment by nwithan8** [comment]
D'oh, good catch, fixed!

**Comment by tomsquest** [comment]
Thanks :+1:
