### ISSUE TITLE
Howto access InfCloud

### ISSUE THREAD

**Issue by EddieFAF** [tomsquest/docker-radicale#155]
Hey there,

I extended the image according to the docs, the image was successfully created and I start the container. Everything is working fine, except I don't know how to get to infcloud. Maybe it has something to do with the UI upgrades within radicale. On older versions I got a link to infcloud in the upper left corner, if I remember that right. With a current version of radicale I don't get that link :(

Any help?!

**Comment by tomsquest** [comment]
Hi @EddieFAF 

I don't know at all as I don't use `infCloud` !

Can you ask there ?

Please re-open if you think that InfCloud is not compatible with the latest version and should be "undocumented".

Thanks

**Comment by parrazam** [comment]
Hi @EddieFAF ,

As you said, the link is no more available in the main webpage, but you can continue accessing directly using:

`https://your.radicale.url/.web/infcloud/`
