### ISSUE TITLE
How to add SSL?

### ISSUE THREAD

**Issue by BuilderZac** [tomsquest/docker-radicale#156]
Hello I am trying to self host this and just connect via localhost from a app on my phone. Only problem is the app does not have a option for non https servers so I need to make it a https connection. As mentioned this is localhost so no domains or 3rd party things are being used. Is there a way I can add a self-signed cert to this container to give me https?

**Comment by tomsquest** [comment]
Hi @BuilderZac ,

I am pretty sure Radicale (the app, not this image) supports custom certificate.
But I strongly encourage use to put Radicale behind a sever, like [Caddy](https://caddyserver.com).
Caddy will handle https for you, so the traffic will be encrypted.
My advice would be to create your own `docker-compose.yml` and declare Caddy and this image into.

I hope this will guide you a bit.
