### ISSUE TITLE
Unable to get RadicaleInfCloud to work

### ISSUE THREAD

**Issue by AaronBenDaniel** [tomsquest/docker-radicale#157]
I can successfully run `docker-radicale` using the provided `docker-compose.yml` and `config` files, but when I try to extend the image to include RadicaleInfCloud the internal webui still shows.

I've created `Dockerfile.extended` with the following contents:

```
FROM tomsquest/docker-radicale

RUN /venv/bin/pip install git+https://github.com/Unrud/RadicaleInfCloud
```

I've run `sudo docker build -t radicale-extended -f Dockerfile.extended .`, altered the image in `docker-compose.yml` from `tomsquest/docker-radicale` to `radicale-extended`, and changed `type = internal` to `type = radicale_infcloud` under the `[web]` header in `config/config`.

The container log shows `web type is 'radicale_infcloud'` but when I go to `localhost:5232` the webui is unchanged.

**Comment by tomsquest** [comment]
Hi @AaronBenDaniel ,

Maybe the issue is on InfCloud. See: https://github.com/Unrud/RadicaleInfCloud/issues/26

You can reopen this issue if not working using the provided fork.

**Comment by AaronBenDaniel** [comment]
This worked! Thank you.
