### ISSUE TITLE
pytz not available inside the venv

### ISSUE THREAD

**Issue by kastel** [tomsquest/docker-radicale#159]
Hello,

I have recently upgraded the `docker-radicale` image and started getting 400 responses from the server (I'm using a mixture of jtxBoard, Errands and Kontact/Akonadi to access the collections). They correlate with this error in the logs:

```
No module named 'pytz'
```

`pytz` is in fact not available inside the venv because it is installed at the system level and is not copied inside the venv. Installing `pytz` using pip instead of as a system package worked for me: https://github.com/kastel/docker-radicale/commit/7d5a21fb1804289a4398d495afdd9ecff9c94883

**Comment by tomsquest** [comment]
Hi @kastel ,

Ah I see. You commit seems totally fine.
I will double check on my side, because I remember finding Radicale listed pytz as a dependency (not an optional one).

**Comment by tomsquest** [comment]
Here is the issue:
https://github.com/Kozea/Radicale/issues/816

It seems that pytz is not used by Radicale, but by vobject, which seems to list it as an optional dep, which I don't find...

**Comment by tomsquest** [comment]
Did the change and released 3.2.3.1

**Comment by kastel** [comment]
Thank you very much for fixing!
