### ISSUE TITLE
.Radicale.lock locking up system

### ISSUE THREAD

**Issue by applesoff** [tomsquest/docker-radicale#164]
I made a mistake of trying to add all calendars to one in outlook with caldavsync and mashed my calendars together. to revert I use duplicati to pull a save i made from the night before. following this and reapplying the correct permissions, I am unable to obtain access to the server. any assistance of fixing this is appreciated.
Please see the error log below:
`radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] Loaded default config
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] Loaded config file '/config/config'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] Starting Radicale
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] auth type is 'radicale.auth.htpasswd'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] auth htpasswd encryption is 'radicale.auth.htpasswd_encryption.bcrypt'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] storage type is 'radicale.storage.multifilesystem'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] rights type is 'radicale.rights.owner_only'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] web type is 'radicale.web.internal'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] hook type is 'radicale.hook.none'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] permit delete of collection: True
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] permit overwrite of collection: True
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] Listening on '0.0.0.0:5232'
radicale  | [2024-11-05 03:14:20 +0000] [7] [INFO] Radicale server ready
radicale  | [2024-11-05 03:14:26 +0000] [7/Thread-1 (process_request_thread)] [INFO] PROPFIND request for '/ericp/8cc0a06d-2c32-90d4-8be3-f19fee3d8588/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:26 +0000] [7/Thread-1 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:26 +0000] [7/Thread-1 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/8cc0a06d-2c32-90d4-8be3-f19fee3d8588/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-2 (process_request_thread)] [INFO] PROPFIND request for '/ericp/594cab03-37fc-d5cb-9a75-e16208c19602/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-2 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-2 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/594cab03-37fc-d5cb-9a75-e16208c19602/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-3 (process_request_thread)] [INFO] PROPFIND request for '/ericp/4188968b-4be6-b924-81c5-05b83d7d1c4d/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-3 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-3 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/4188968b-4be6-b924-81c5-05b83d7d1c4d/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-4 (process_request_thread)] [INFO] PROPFIND request for '/ericp/8bdc9bfa-b6c5-7227-c41c-ab1cec7d6ad1/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-4 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-4 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/8bdc9bfa-b6c5-7227-c41c-ab1cec7d6ad1/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-5 (process_request_thread)] [INFO] PROPFIND request for '/residents/82a30865-3de5-4fe8-8ba4-d1ce97f26985/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-5 (process_request_thread)] [INFO] Successful login: 'residents'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-5 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/residents/82a30865-3de5-4fe8-8ba4-d1ce97f26985/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:27 +0000] [7/Thread-6 (process_request_thread)] [INFO] PROPFIND request for '/residents/e6d92dd5-29ff-40e3-b18e-aab5d56a9f87/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-6 (process_request_thread)] [INFO] Successful login: 'residents'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-6 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/residents/e6d92dd5-29ff-40e3-b18e-aab5d56a9f87/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-7 (process_request_thread)] [INFO] PROPFIND request for '/residents/82a30865-3de5-4fe8-8ba4-d1ce97f26985/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-7 (process_request_thread)] [INFO] Successful login: 'residents'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-7 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/residents/82a30865-3de5-4fe8-8ba4-d1ce97f26985/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-8 (process_request_thread)] [INFO] PROPFIND request for '/ericp/594cab03-37fc-d5cb-9a75-e16208c19602/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-8 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-8 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/594cab03-37fc-d5cb-9a75-e16208c19602/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-9 (process_request_thread)] [INFO] PROPFIND request for '/ericp/4188968b-4be6-b924-81c5-05b83d7d1c4d/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-9 (process_request_thread)] [INFO] Successful login: 'ericp'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-9 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ericp/4188968b-4be6-b924-81c5-05b83d7d1c4d/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-10 (process_request_thread)] [INFO] PROPFIND request for '/residents/e632f7d0-392c-db2e-6c08-2261c51c74fc/' with depth '0' received from 172.16.192.1 (forwarded for '73.176.36.49') using 'DAVx5/4.4.3.2-ose (dav4jvm; okhttp/4.12.0) Android/14'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-10 (process_request_thread)] [INFO] Successful login: 'residents'
radicale  | [2024-11-05 03:14:28 +0000] [7/Thread-10 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/residents/e632f7d0-392c-db2e-6c08-2261c51c74fc/': [Errno 13] Permission denied: '/data/collections/.Radicale.lock'`

**Comment by tomsquest** [comment]
Hi @applesoff ,

From what I see, `/data/collections/.Radicale.lock` has incorrect permission. Maybe the file was created by `root`, then the configuration was changed to a given user which, then, cannot read the file anymore.

**Comment by applesoff** [comment]
Gotcha. I fixed it by restarting the container from scratch and then just adding the files to the collections-root. If it happens again then I'll know it's permissions. Thank you!

**Comment by tomsquest** [comment]
:+1:  well done !
