### ISSUE TITLE
Sync Issue with Tasks/Reminders (Docker on Synology DS920+)

### ISSUE THREAD

**Issue by ReptiloidAffluent** [tomsquest/docker-radicale#167]
Good Afternoon,

## Setup Details:
- **Platform**: Synology DS920+
- **Radicale Deployment**: Running in Docker, accessed through Synology's reverse proxy.
- **Databases**:
  - Calendar: Includes calendar, journal, and tasks.
  - Contacts: Includes the address book.
- **Clients**:
  - iPhone (using CalDAV/CardDAV for Calendar, Contacts, and Reminders).
  - Thunderbird (for Calendar, Contacts, and Tasks).

## Current Behavior:
- Calendar events sync perfectly between Thunderbird and iPhone.
- Contacts sync seamlessly as well.
- Tasks (or iOS Reminders):
  - I can add tasks on either device, and they sync bidirectionally without issue.
  - **Problem**: When I mark a task as completed on either Thunderbird or iPhone, the status does not sync to the other device.

## Question:
Are there any specific configurations required in **Radicale**, **Thunderbird**, or **iOS** to ensure that task/reminder completion statuses sync properly? 

Here is my compose file in case it helps:

```yml
services:
 radicale:
  image: tomsquest/docker-radicale
  container_name: radicale
  ports:
   - 5232:5232
  init: true
  security_opt:
   - no-new-privileges:true
  cap_drop:
   - ALL
  cap_add:
   - SETUID
   - SETGID
   - CHOWN
   - KILL
  deploy:
   resources:
    limits:
     memory: 256M
     pids: 50
  healthcheck:
   test: curl -f http://127.0.0.1:5232 || exit 1
   interval: 30s
   retries: 3
  restart: unless-stopped
  volumes:
   - /volume2/docker/radicale:/data
  environment:
   - PUID=1026
   - PGID=100

**Comment by tomsquest** [comment]
Hi @ReptiloidAffluent ,

This seems/may be a problem with Radicale itself.

Can you open an issue on their side?
https://github.com/Kozea/Radicale/issues
