### ISSUE TITLE
Incorrect ports attribute in docker-compose.yml

### ISSUE THREAD

**Issue by vfedetz** [tomsquest/docker-radicale#170]
I could not get the radicale web ui to work until I modified this line from the docker-compose.yml file:

```
    ports:
      - 127.0.0.1:5232:5232
```

to this:

```
    ports:
      - 5232:5232
```

Is this a bug?

**Comment by tomsquest** [comment]
Hi @vfedetz ,

I double check and it's working fine, and as intended.

Given a port `127.0.0.1:5232:5232`, we open port 5232 on the host and only local to this machine.
If the port was defined as `5232:5232`, the port 5232 on the host will be open to everyone.

![image](https://github.com/user-attachments/assets/a727d1ca-3621-494b-9f9e-3f3e26686d2d)
https://docs.docker.com/engine/network/#published-ports

With `5232:5232` (open to any ip):

```
❯ docker port 253c1935811c             
5232/tcp -> 0.0.0.0:5232
5232/tcp -> [::]:5232
```

With `127.0.0.1:5232:5232`:

```
❯ docker port 5312a97a9e86                    
5232/tcp -> 127.0.0.1:5232
```
(only local is allowed)

Conclusion:
There is no problem if your host has a firewall and does not accept connection from those ports.
