### ISSUE TITLE
[FATAL tini (8)] exec docker-entrypoint.sh failed: Exec format error

### ISSUE THREAD

**Issue by p-m-o** [tomsquest/docker-radicale#32]
Hi,

first of all thank you for your work.
I am using radicale more than one year now with a normal installation on a raspberry pi and want to change over to docker.
When I try to start your container on a pi I get the error mentioned in the headline.
The same configuration runs without any problem with docker on windows.

I checked out the repository from github and found that the lines in the script and some other files end with "crlf".
After changing eol from "crlf" to "lf" only and rebuilding the container on the pi the script works as expected.
Can you have a look at this ?

**Comment by tomsquest** [comment]
Hi @p-m-o,

Line endings seems already be of linux type:

```
$ file docker-entrypoint.sh                                              
docker-entrypoint.sh: POSIX shell script, ASCII text executable
```

No so obvious, but forcing the line endings to DOS/Windows type:
```
$ unix2dos docker-entrypoint.sh 
unix2dos: converting file docker-entrypoint.sh to DOS format...
$ file docker-entrypoint.sh    
docker-entrypoint.sh: POSIX shell script, ASCII text executable, with CRLF line terminators
```

Maybe, the checkout process or copy from one FS to another mangled the line endings.

**Comment by p-m-o** [comment]
Hello tomsquest,

thank you for your quick reply.
I totally agree with your explanations.
As far as I found out now line endings are adjusted according to the system (windows , linux, ...)  when you check out with a default git configuration.
Therefore the endings might have been changed when I checked out on windows. Sorry for that.
The reason for checking out was that the original image pulled on the pi (docker pull tomsquest/docker-radicale:latest) cannot be started and shows the error mentioned in the title.
I now checked out directly on the pi. Line endings are ok.
After rebuilding the image on the pi it can be started without error.
After all I think that image has to be rebuild because the pi is ARM based.
Sorry for my misunderstanding, but I'm just getting started with Docker.

**Comment by tomsquest** [comment]
Hello,

We added recently multi-architecture builds. This means there are different builds of the image.
You can have a look at the tags: https://hub.docker.com/r/tomsquest/docker-radicale/tags/

You can pull latest arm with: `docker pull tomsquest/docker-radicale:arm`
