### ISSUE TITLE
`/config` could be readonly

### ISSUE THREAD

**Issue by tomsquest** [tomsquest/docker-radicale#33]
Currently, `/config` is writeable (`chmod 700 /config`).
As radicale should only be able to write in `/data`, this could be a good idea.

@robertbeal what do you think of it? Good idea?

**Comment by robertbeal** [comment]
Definitely. 400 (r) or 500 (rx) rights? I guess 400 would be preferable, hope that's enough for Radicale.

When mounting the config the user can specify `:ro` but I think it's good practice to set it correctly in the container especially if someone runs off the default config.

**Comment by tomsquest** [comment]
Currently, `/config` is owned by `radicale` but the `/config/config` is owned by root (even with the is `chmod 700` because the `COPY config...` is done *after* the chmod.
The resulting rights are for `/config/config`: `554 root:root`.

I am working on it.
