### ISSUE TITLE
Helthcheck uses http-based url while running server on https

### ISSUE THREAD

**Issue by kimpenhaus** [tomsquest/docker-radicale#44]
Howdy,

while facing such SSL error which was repeating every 30 seconds

`ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)`

I was looking for the cause. All my clients were already moved to use https, so it took me a while to find it. It looks like that the health-check is using a hardcoded `http` request:

`HEALTHCHECK --interval=30s --retries=3 CMD curl --fail http://localhost:5232 || exit 1`

I didn't find any chance to redirect http requests to https nor found any possibility to expose an http and a different https port.

The container itself shows as unhealthy because of the requests throwing errors.
Is there any chance to have a work-around for this? Is it possible to have a fallback url (https-based) on the curl command?

Thanks,
Marcus

**Comment by kimpenhaus** [comment]
I found a working solution! `docker create` gives the possibility to override the health check command. So I just changed the command to:

`--health-cmd='curl --fail https://localhost:5232 || exit 1' --health-retries=3  --health-interval=30s`

I should have searched better before ;-) Just closing this issue.

**Comment by tomsquest** [comment]
Thanks @kimpenhaus for the info. It could have beaten me.
