### ISSUE TITLE
Add volume for config

### ISSUE THREAD

**Issue by Loader23** [tomsquest/docker-radicale#5]
Hi,

it would be alot easier if we had a volume for the config file. Could you implement that?

**Comment by tomsquest** [comment]
Sure ! Good idea.

I will do it soon.

Thx

**Comment by Loader23** [comment]
That would be great, thanks alot 👍

**Comment by tomsquest** [comment]
Implemented in branch https://github.com/tomsquest/docker-radicale/tree/config-volume

Can you test if it suits your need ?

I will do some more testing on my own host later.

**Comment by Loader23** [comment]
Sorry for the late answer :-)
Could not get it running, iam using docker on QNAP and things might be different there. I tried it with the build command but no luck. Iam only used to the docker pull command from docker hub, never used something else.
But looks good though 👍

**Comment by Loader23** [comment]
Sorry when iam annoying, but could you include that change in your master or make an own entry for Docker Hub? So that I can use it with a pull command?

**Comment by tomsquest** [comment]
Yes, the change seems good. I will try to merge it in the following days.
-- 
Thomas Queste
http://www.tomsquest.com

**Comment by Loader23** [comment]
Awesome :-) Thanks alot!

**Comment by Loader23** [comment]
Just want to say thank you!
I set it up today and its working perfect, thanks alot! 👍
