### ISSUE TITLE
Fail to load infcloud

### ISSUE THREAD

**Issue by lifehome** [tomsquest/docker-radicale#62]
After configuring radicale to load `radicale_infcloud`, the following error popped out:
```
ERROR: An exception occurred during server startup: Failed to load web module 'radicale_infcloud': No module named 'radicale_infcloud'
```

Seems weird, is this a bug to #17?

**Comment by tomsquest** [comment]
Hi,

How did you configured the container to load_infcloud ?
What is your config file?

**Comment by WunderWaffla** [comment]
Hi.
Can confirm, I've got the same error.
I'm enabling infcloud with this setting in config file:
```
[web] 
type = radicale_infcloud
```
with `type = none` it starts and works

**Comment by tomsquest** [comment]
Did you include the infcloud package in your container, as in [this section](https://github.com/tomsquest/docker-radicale#extending-the-image) of the documentation ?

Re-reading the doc, I see that there is still a mention of infcloud in the header. This package was removed lately in favor of extending the image.

**Comment by WunderWaffla** [comment]
Oh. I see now. I updated my installation and encountered this error. Looks like my version was a little old :/
Thanks for the info.
