### ISSUE TITLE
Latest release tag

### ISSUE THREAD

**Issue by larsskj** [tomsquest/docker-radicale#63]
Please add a latest release tag like the upstream repo has.
This makes automated builds a lot easier.

**Comment by tomsquest** [comment]
Hi @larsskj ,

I think `latest` already exist:

```bash
$ docker pull tomsquest/docker-radicale:latest
latest: Pulling from tomsquest/docker-radicale
...
```

**Comment by larsskj** [comment]
Hi @tomsquest,
You're right that latest exist as a Docker label - ie. for the Docker image.
But it does not exist as a Github label. I build my own Radicale images inheriting from yours - I have to in order to add LDAP authentication.
This is much easier to automate if your Github repo has a latest tag as well.
Best regards
Lars

**Comment by tomsquest** [comment]
I created the `latest` tag (https://github.com/tomsquest/docker-radicale/releases) and made it be skipped when push on TravisCI.

**Comment by larsskj** [comment]
Hi @tomsquest ,

Thank you for being responsive.

I'm not an expert on these matters, but it appears that your latest tag does not point to the latest release - ie. 2.1.11.4:

![Radicale latest](https://user-images.githubusercontent.com/7857959/71217729-fd7a4200-22be-11ea-9253-aa3b46cc3a94.png)

whereas on the upstream the latest tag points directly to the latest release as I've become used to:

![Radicale latest upstream](https://user-images.githubusercontent.com/7857959/71217757-197de380-22bf-11ea-8451-228ec1facb74.png)

But maybe this will be fixed upon the next regular build?

Best regards,
Lars

**Comment by tomsquest** [comment]
Oh I see the point: in fact, this docker image incorporates Radicale. The version of the Docker image and the version of Radicale does not match physically (a commit on Radicale is not a commit on Docker-Radicale), but more logically : I manually pick the chosen tag of the Docker image, based on the tag of Radicale. There is no direct link.
