### ISSUE TITLE
Docker image from latest master?

### ISSUE THREAD

**Issue by rngtng** [tomsquest/docker-radicale#66]
As the last release 2.1.11 of radicale is quite a while ago, is there a way to get an image from latest master?
Like an experimental/nightly build or pre-release? Would it be as simple as updateing `Dockerfile` line 33?

```
...
&& python3 -m pip install git+https://github.com/Kozea/Radicale.git@master passlib[bcrypt] \
...
```

Thx

**Comment by tomsquest** [comment]
Yes, this would work. 
Maybe you can do this from a child Dockerfile:

```dockerfile
FROM this-image

RUN python3 -m pip install git+https://github.com/Kozea/Radicale.git@master
```

This should update Radicale to `master` and still benefit from any update on this image.

**Comment by rngtng** [comment]
true good point, I'll give it a try thx
