### ISSUE TITLE
"Address not available" when starting docker

### ISSUE THREAD

**Issue by northorsouth** [tomsquest/docker-radicale#67]
Hello, I'm having an issue starting this docker container on my unraid server. I'm using the "production" config with all the extra parameters provided. It starts successfully when I don't include the "hosts" field in the config, but I can't access the webUI. If I add in my server URL in the hosts field, I see an error saying "address not available". I have port 5232 exposed.

**Comment by tomsquest** [comment]
Hi,

The `host` field is somewhat internal to the container, and _shouud_ stay as `0.0.0.0`. It tells Radicale to accept connection from anywhere. Docker will send connection to the container with an address that is not `127.0.0.1`, so it is easier to not restrict the access that way. And it should not be your server URL, which the container does not know anything.

The issue maybe the frontend (nginx, apache, caddy, traefik) that unraid setup on top of it. And for that case, I can't help.

**Comment by northorsouth** [comment]
I still can't access the webui, even if I go directly to lan-ip:5232. So i don't think its the proxy. But 0.0.0.0 is the default right? So I should just leave the hosts line out of the config?

-------- Original Message --------

**Comment by tomsquest** [comment]
No, the default is `127.0.0.1` for security purpose (when Radicale runs *on* the host)

**Comment by northorsouth** [comment]
Ah, that was my issue. Working now with 0.0.0.0:5232, also proxied to port 80. Thanks for the help!

-------- Original Message --------

**Comment by shasycouk** [comment]
> Ah, that was my issue. Working now with 0.0.0.0:5232, also proxied to port 80. Thanks for the help!
> […](#)

Hi there, sorry for having to write in this issue, but I wasn't able to find many people that are running this on unRAID. I can get the docker to work in its standard configuration but I'm having problems with properly setting it up. Would you mind sharing your unRAID radicale docker configuration (in advanced view)? @northorsouth Alternatively, If you would rather not share it here, I'd appreciate an email (shasycouk@pm.me) or a dm on twitter (benediktLEB). Thanks ahead.
