### ISSUE TITLE
cannot open /etc/group

### ISSUE THREAD

**Issue by JustNoopie** [tomsquest/docker-radicale#72]
Hey guys,

first of all I want to thank you for this piece of work. It's a good thing to start with as a linux/docker freshman.

Following the instructions, I would like to start the container the production-grade way.
The directories on the host system have been created and adapted in the start command of the container.

```
docker run -d --name radicale \
-p 127.0.0.1:5232:5232 \
--read-only \
--init \
--security-opt="no-new-privileges:true" \
--cap-drop ALL \
--cap-add CHOWN \
--cap-add SETUID \
--cap-add SETGID \
--cap-add KILL \
--pids-limit 50 \
--memory 256M \
--health-cmd="curl \
--fail http://localhost:5232 || exit 1" \
--health-interval=30s \
--health-retries=3 \
-v /media/NAS/opt/radicale/data:/data \
-v /media/NAS/opt/radicale/config:/config:ro \
tomsquest/docker-radicale
```

As soon as I type the command, the container goes into the "Exited" status. The logs of the container get me this message:

```
root@server:~# docker container logs radicale
groupmod: cannot open /etc/group
groupmod: failed to unlock /etc/group
```

Permissions of the directories:
```
root@server:~# ls -la /media/NAS/opt/radicale/
total 16
drwxr-xr-x 4 root     root     4096 Mär 21 10:03 .
drwxr-xr-x 3 root     root     4096 Mär 21 09:37 ..
drwxr-xr-x 2 root     root     4096 Mär 21 09:56 config
drwxrwx--- 2 radicale radicale 4096 Mär 21 10:03 data
```

I guess I'm reaching the limits of my narrow knowledge here.

Do you have any ideas?

Thanks

**Comment by JustNoopie** [comment]
I guess, this error is currently known. I'm sorry for duplicating this.

**Comment by tomsquest** [comment]
Hi @JustNoopie . Yes, sorry that the current tag is broken. A fix exists, I will merge it ASAP.
