### ISSUE TITLE
QUESTION: How do I create a single user account?

### ISSUE THREAD

**Issue by john-catalano** [tomsquest/docker-radicale#78]
On my macOS Catalina system running docker, I can run the image, login to the web UI with any username/password, and even access the web UI from outside of my network.

I want to create a single user account, just for me. How should I do this? I looked to do it via htpasswd, but I cannot find that within the image.

These instructions look promising, but I am unfamiliar with adding users via the terminal. Would I run this from within the container, or from the host macOS system?

sudo addgroup --gid 2999 radicale
sudo adduser --gid 2999 --uid 2999 --shell /bin/false --disabled-password --no-create-home radicale

And, I do want a password, so should I leave out "--disabled-password"?

**Comment by tomsquest** [comment]
Hi @john-catalano ,

I am in the same condition as you: I run Radicale just for myself.
So basically we run without user management, so we don't need password and authentication.
The `config` file is setuped for that (one can change it to check account, setup an admin and so on).
This is particular to Radicale and I don't know much about user management by Radicale itself.

The user/group instruction from your comment is not relevant for user management in Radicale. It is only used for files and permissions, not for Calendars.

So in your case (and mine a couple years ago), I just created new Calendars using Thunderbird, using a username (eg. `tom`) and any password. Radicale won't check for a password (as per the config) and the calendar will be created. That's it, nothing more to configure.

**Comment by john-catalano** [comment]
I wish to use a defined account name and password (and reject all others). I will look to do this via the /config/config file. Thank you.

**Comment by tomsquest** [comment]
You're welcome.

FYI, I use auth provided by Caddy, my web server (basic auth on https). This works fine.
