### ISSUE TITLE
Upgrade to Radicale 3.x

### ISSUE THREAD

**Issue by TribuneX** [tomsquest/docker-radicale#81]
Do you plan do upgrade this docker image to the latest version 3.0.4 of Radicale?

**Comment by tomsquest** [comment]
Hi @TribuneX , yes I would like to. I still have to read the changelog, adapt it, test it locally, then on my personal data, then release.
I will do it in a separate branch, with a docker image tagged `v3`.

**Comment by GreyMarvel** [comment]
Hi @tomsquest is there any update on this ? There are a couple of features I'm interested in on the 3.0 branch and I'm far from smart enough to create my own docker container equal to the security of yours.

Thanks again for create an easy to use Radicale docker .

**Comment by tomsquest** [comment]
Hi @TribuneX and @GreyMarvel 

I took some time to update to Radicale v3. 
The image has been pushed as `tomsquest/docker-radicale:v3-test`. 
It is an upgrade to Radicale 3.0.6.
See PR #84 

Can you try and give it a go?

**Comment by GreyMarvel** [comment]
Hi @tomsquest sorry in the delay getting back to you , I will trial the 3.x branch and pass any feedback to yourself over the next couple of weeks . Thanks again for your hard work.

**Comment by TribuneX** [comment]
HI @tomsquest. I am running radicale on an ARM based server. Therefore, I need to wait for an ARM version of the v3 image. Thanks for your effort.

**Comment by GreyMarvel** [comment]
@TribuneX  on the main page it shows that it's still suitable for multi architecture, including arm . It just requires stating the image required not latest. Like the 2.1 branch .

    tomsquest/docker-radicale:386.3.0.6.0
    tomsquest/docker-radicale:amd64.3.0.6.0
    tomsquest/docker-radicale:arm.3.0.6.0
    tomsquest/docker-radicale:arm64.3.0.6.0

Hope this helps

**Comment by tomsquest** [comment]
@TribuneX I only pushed the amd64 version as it was built locally.

So far, everything is good with v3. I will merge it to master and release in a few days if everything is ok.

**Comment by tomsquest** [comment]
PR has been merged.
A release, `3.0.6.0` will follow soon.

**Comment by GreyMarvel** [comment]
hi @tomsquest , Ive been using the 3.0 branch for a week now and its brilliant , no issues to report . 

Thank you so much for your efforts and for providing the container image

**Comment by tomsquest** [comment]
You're welcome @GreyMarvel !
