### ISSUE TITLE
unable to change path of config file

### ISSUE THREAD

**Issue by eliaharm** [tomsquest/docker-radicale#85]
Hello,

I am using nomad to run the container and storing the config file in "/local/config" as it is being generated from a consul template.

however I am unable to change the location of the config file using the environment variable as I think it is being overwritten with line 56 of the docker file
```
CMD ["radicale", "--config", "/config/config"]
```
is it possible to remove the --config parameter and leave it as an environment variable?

Thanks,

**Comment by tomsquest** [comment]
Hi @eliaharm ,

Two things:

- You can override the CMD/Entrypoint instruction in your docker-compose if you wish

See [docker-compose reference](https://docs.docker.com/compose/compose-file/compose-file-v3/#entrypoint)

- I am a bit surprised : if the file is store in `/local/config` on the **host**, then it can be mounted in the correct location in the **container**, ie. `/config`

**Comment by eliaharm** [comment]
Hello @tomsquest 

Thank you, yes I have figured out how to override CMD. that was the first time I had to do that.

Actually it is not on the host, I think some sort of chroot tha Hashicorp Nomad uses as I didn't want to create a volume for a single file and also to keep the configuration parameters in consul (12 factor app config guidelines...)

Best,
Elia
