### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "operation not permitted"

### ISSUE THREAD

**Issue by chris-fh** [tomsquest/docker-radicale#86]
Hi,

I cannot start up the container in the current setup using it with traefik ssl termination (which is needed to use with Mac Clients).
I have a second setup in a virtualbox, also with traefik ssl termination it works fine.

When checking docker logs I only get the following line:
standard_init_linux.go:211: exec user process caused "operation not permitted"

I have tried running the container in privileged mode without "cap_drop..." I have tried without "read_only: true", still the same error message.

Any help you can give will be appreciated.

**Comment by tomsquest** [comment]
hi @chris-fh ,

Did you try with the simplest instructions first (ie. no security stuff) ?

```
docker run -d --name radicale \
    -p 5232:5232 \
    tomsquest/docker-radicale \
    -v /radicale/data:/data \
    -v /radicale/config:/config:ro \
```

It may be a permission problem due to the `--cap-add`, `--cap-drop`, `--security-ops` or simply the volume not mounted correctly I think.

**Comment by tomsquest** [comment]
Closing.
