### ISSUE TITLE
Git clone every time on startup and return fatal error

### ISSUE THREAD

**Issue by nuxlight** [tomsquest/docker-radicale#87]
Hi

I think they are a problem with Git on container startup.
If you already have a cloned repo, the git command return fatal error and container go down :(

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Recreating radicale ... done
Attaching to radicale
radicale    | fatal: destination path '/data/collections' already exists and is not an empty directory.
radicale exited with code 128
```

**Comment by tomsquest** [comment]
Hi @nuxlight ,

Totally agree. 
Now that you report this, I totally agree : there is no test that check if the repo already exists or not.

I am thinking about that feature of cloning the repo, as in "I think that feature does not belong to this image", aka I should get rid of it and people will create the repo themselves in the container if they want it.
And also less code, less maintenance, less complex image.

There is a PR about trying to solve the issue #88 that to study.

In the meantime, you can just remove the `GIT_*` variable and then no Git cloning will be run and that will be fine.

**Comment by tomsquest** [comment]
Version 3.0.6.1 (being built right now) removes git cloning using env vars.
See: https://github.com/tomsquest/docker-radicale/commit/3e4e286f21e9fc4d4a0e380522d8db98f7fa9c74

So no feature = no bug :/
