### ISSUE TITLE
Can't get server to authorise connection

### ISSUE THREAD

**Issue by shasycouk** [tomsquest/docker-radicale#89]
Hi there,

I've been trying to get radicale running on my unRAID server and I managed to do so both using the minimal and the production-grade instruction from the readme. I logged in/created an account and then imported my Google Calendar (worked flawlessly). At this point, adding the calendar to a client (here: Calendar on Mac OS) worked, but the client told me after a few minutes that no connection could be made (makes sense, it added the calendar as no users were set up but connection was not possible still)

I then went on and edited the config a little bit, by adding plain text users (I know.. but that's ok, server is only reachable within the local network) and some other things. Apple Calendar now tells me that it is unable to very my account name and password (which is great: I know auth is at least activated). 

My current config and users file can be found here, as well as the logs: https://pastebin.com/tVEUGk70

**Any help is appreciated. Thanks so much for your docker!**

**Comment by tomsquest** [comment]
Hi @shasycouk 

You are really on your own on that.
Very hard to troubleshoot a setup that I don't have (unraid, apple stuff).
