### ISSUE TITLE
publish a 1.1.7 version of radicale

### ISSUE THREAD

**Issue by oupala** [tomsquest/docker-radicale#90]
Would you agree in publishing a 1.1.7 version of radicale as a docker image so that the container can be used to migrate data from 1.x version t 2.x version?

1.1.7 is the last 1.x version and contains the raquired code to convert data.

debian bullseye will be out in a few months and is providing radicale 2.x by default as the current stable version of debian is providing radicale 1.x by default. There should be a lot of migration in the newt year.

**Comment by tomsquest** [comment]
Hi @oupala ,

This image never supported Radicale 1.x.
That would be too much for me : write, test, maintain.
Sorry, the response is no.

**Comment by oupala** [comment]
Ok. I just asked because I saw that your docker image was available with tags [1.1.0](https://hub.docker.com/layers/tomsquest/docker-radicale/1.1.0/images/sha256-221ebeec91f85bdbd284c9887faf8bd075e123781fe8ecd3d567072289dbfb75?context=explore) and [1.1.1](https://hub.docker.com/layers/tomsquest/docker-radicale/1.1.1/images/sha256-92cf8f025da846a1b0da9bbd225b38ae5b1c9cf169b34bbc6ff4ef069f397143?context=explore) so I tought that Radicale 1.x was supported.
