### ISSUE TITLE
Feature request: support UMASK environment variable

### ISSUE THREAD

**Issue by Miwer** [tomsquest/docker-radicale#93]
Hi, 

It would be great if the docker-entrypoint.sh could support providing a UMASK variable, and set this using the umask command before running radicale.
Currently data files created by this image is readable by "all", but I would like to use umask 027, so only owner/group ID is able to read the data files.

Thanks ;)

**Comment by tomsquest** [comment]
Hi @Miwer ,
That could be a good feature.
Do you have a Docker image that do so?

**Comment by tomsquest** [comment]
PR welcome, don't forget to add an integration tests.
