### ISSUE TITLE
versioning not working.

### ISSUE THREAD

**Issue by luckydonald** [tomsquest/docker-radicale#94]
I tried to set it up exactly how instructed, but I can't see it commit after changing stuff.

Should it somehow print debug when executing those git commands?
The logs so far stay empty.

I have no real clue what might be going on as I can't see anything related to that hook at all in the logs.

**Comment by tomsquest** [comment]
I don't know at all how and if Radicale logs stuff on commit.

Somehow it is not related to this project, which is more about bundling Radicale in a safer Docker container.
I will close this issue. I do think you should ask on the proper Radicale channels.

**Comment by luckydonald** [comment]
I disagree with closing this issue, because it is not about the logging here.

Instead it is about the feature of this container (the git hook thing) not working.

I mean I don't mind raising an issue there for having that logging to be better, but at the current state the way proposed in this repo’s readme is not working.

**Comment by tomsquest** [comment]
I reopened the issue : I saw a difference between the official doc and the section in the readme:

The official doc hook is: `git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)`

Can you try with this ?
Can you also try to increase the log level of Radicale. 

And did you create the git repo (`git init`, official doc) or did you follow the steps of the readme ?

**Comment by tomsquest** [comment]
I reviewed our doc, and somehow I am not sure we should describe how to integrate with Git, as it is already in the official documentation of Radicale ; and for us, this is a potential source of errors (and support to do like this issue).

I removed the section in c82e2bb41daa8dc2eef1d87ded26f006aaaa0898

**Comment by shtingeri** [comment]
It seems you are complaining more about git hook not working than little info in the logs.
I came across the similar issue.
Luckily I found [this](https://github.com/Kozea/Radicale/issues/1181#issuecomment-914209910).
Thus, I changed the hook command to `hook = ([ -d .git ] || git init && git config user.name user && git config user.email user@example.com && echo -e ".Radicale.cache\n.Radicale.lock\n.Radicale.tmp-*" > .gitignore) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)`
Not sure if it works for you.
